# Generated by Django 4.1.7 on 2023-03-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correodummy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=50)),
                ('clave', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'TablaDummy',
                'verbose_name_plural': 'dumys',
            },
        ),
    ]
